# Generated by Django 4.1 on 2022-08-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='taggs',
        ),
        migrations.AddField(
            model_name='news',
            name='taggs',
            field=models.CharField(default='max', max_length=100, verbose_name='Теги'),
        ),
    ]
